[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "carla-icts2"
version = "0.0.1"
description = "CARLA-ICTS2"
authors = [{ name = "Camilo Martínez M.", email = "cama02@dfki.de" }]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.10,<3.11"

[tool.ruff]
line-length = 99
target-version = "py310"

[tool.ruff.lint]
select = [
    "ALL", # include all the rules, including new ones
]

ignore = [
    "D413",
    "TRY003",  # Avoid specifying long messages outside the exception class
    "EM102",   # Exception must not use an f-string literal, assign to variable first
    "SIM108",  # Use ternary operator `prev_timestamp = value[-1] if isinstance(value, list) else value` instead of `if`-`else`-block
    "PLR5501", # Use `elif` instead of `else` then `if`, to reduce indentation
    "ERA001",  # Found commented-out code
    "T201",    # `print` found
    "BLE001",  # Do not catch blind exception: `Exception`
    "C901",    # `add_sequential_seconds` is too complex (13 > 10)
    "PLR0912", # Too many branches (13 > 12)
    "UP031",   # Use format specifiers instead of percent format
    "S101",    # Use of `assert` detected
    "EM101",   # Exception must not use a string literal, assign to variable first
    "PLR0913", # Too many arguments in function definition (6 > 5)
    "PLR0915", # Too many statements (65 > 50)
    "TRY301",  # Abstract `raise` to an inner function
    "PTH207",  # Replace `glob` with `Path.glob` or `Path.rglob`
    "PTH103",  # `os.makedirs()` should be replaced by `Path.mkdir(parents=True)`

    # Actually, just ignore all PTH rules
    "PTH",
]

[tool.ruff.format]

# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.mypy]
disable_error_code = ["import-untyped"]

[[tool.mypy.overrides]]
module = ["carla.*"]
ignore_missing_imports = true