# Runtime Configuration
carla:
  path: "/home/camilo/Applications/carla-0-9-15-linux"
  quality: "Low" # Options: "Low"
  port: 2000
  server_mode: true # Whether to launch CARLA in server mode
  fps: 25
  prevernvidia: true
  benchmark: true
  carla_server: true
  set_variables: ["DRI_PRIME=1"]
  max_episode_length: 300 # Maximum number of frames in an episode, 500
  iterations: 1 # Force the number of iterations to this value, set to 1 for testing
  width: 800 # Width of the camera
  height: 600 # Height of the camera
  load_complete_map: true # Whether to load the complete map, False will load a simplistic map

# Logic Configuration
scenarios: [
    "01_int",
    # "02_int",
    # "03_int",
    # "04_int",
    # "05_int",
    # "06_int",
    # "01_non_int",
    # "02_non_int",
    # "03_non_int",
    # "04_non_int",
    # "05_non_int",
    # "06_non_int",
  ]

# Camera Configuration
camera: ["vehicle_pov"] # Possible are: ["pedestrian_pov", "vehicle_pov", "bev_static", "bev_follow_vehicle", "bev_follow_pedestrian", "default"]

# Video Configuration
video:
  save: true # Whether to save the video
  save_frames: true # Whether to save the frames in output/videos/frames folder
  fps: 25 # Frames per second for the output video

  # Whether to use ffmpeg for video encoding
  # Otherwise, it will use cv2.VideoWriter by default
  use_ffmpeg: true

  output_path: "output/videos" # Path to save the video
  scenario_as_folder: true # Whether to use the scenario name as a folder inside the output path
  camera_in_filename: true # Whether to use the camera name in the filename
  filename: "view" # Filename of the video
  format: "mp4" # Format of the video, options: "avi", "mp4", "mkv"

