# Runtime Configuration
carla:
  path: "/home/camilo/Applications/carla-0-9-15-linux"
  quality: "Epic" # Options: "Low"
  port: 2000
  server_mode: true # Whether to launch CARLA in server mode
  fps: 25
  prevernvidia: true
  benchmark: true
  carla_server: true
  set_variables: ["DRI_PRIME=1"]
  max_episode_length: 100 # Maximum number of frames in an episode, 500
  iterations: 1 # Force the number of iterations to this value, set to 1 for testing

# Logic Configuration
scenarios: [
    "01_int",
    # "02_int",
    # "03_int",
    # "04_int",
    # "05_int",
    # "06_int",
    # "01_non_int",
    # "02_non_int",
    # "03_non_int",
    # "04_non_int",
    # "05_non_int",
    # "06_non_int",
  ]

# Camera Configuration
camera: ["bev_follow_vehicle"] # Possible are: ["pedestrian_pov", "vehicle_pov", "bev_static", "bev_follow_vehicle", "default"]

# Video Configuration
video:
  save: true # Whether to save the video
  save_frames: true # Whether to save the frames in output/videos/frames folder
  fps: 25 # Frames per second for the output video
  output_path: "output/videos/spectator_view.mp4" # Path for the saved video
